# Generated by Django 5.2.6 on 2025-09-05 14:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('specialization', models.CharField(choices=[('GP', 'General Practitioner'), ('CARD', 'Cardiologist'), ('NEURO', 'Neurologist'), ('ORTHO', 'Orthopedist'), ('DERMA', 'Dermatologist'), ('PEDIA', 'Pediatrician'), ('GYNEC', 'Gynecologist'), ('PSYCH', 'Psychiatrist'), ('ONCO', 'Oncologist'), ('EMERG', 'Emergency Medicine')], max_length=10)),
                ('license_number', models.CharField(max_length=50, unique=True)),
                ('phone_number', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.TextField()),
                ('experience_years', models.PositiveIntegerField()),
                ('consultation_fee', models.DecimalField(decimal_places=2, max_digits=10)),
                ('available_hours', models.CharField(help_text='e.g., Mon-Fri 9AM-5PM', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctors', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
